site_name: Inazuma Eleven Heroes Victory Road Documentaci√≥n

nav:
  - Inicio: index.md
  - About: about.md

theme:
  name: material
  language: es
  palette:
    primary: blue
    accent: amber
  font:
    code: Roboto